name: Build Docker image

# To trigger via API
# curl \
#     -X POST \
#     -H "Accept: application/vnd.github.v3+json" \
# --header 'Authorization: token ******' \
# https://api.github.com/repos/octocat/hello-world/dispatches \
#     -d '{"ref":"main", "inputs": { "name":"Command Line User", "home":"CLI" }}'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jahia/cimg-mvn-cache:ga_cimg_openjdk_8.0.312-node
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    env:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_INTERNAL_URL: https://devtools.jahia.com/nexus/content/groups/internal/
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          cd docker-jahia
          mvn -B -s ../.github/maven.settings.xml clean install
          docker push jahia/jahia-next:8.1.2.0-SNAPSHOT
